<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories=array(
            array('name'=>'Android development')
            ,array('name'=>'Dynamic website design')
            ,array('name'=>'Php development')
            ,array('name'=>'Back end development')
            ,array('name'=>'iPhone app development')
            ,array('name'=>'Digital marketing')
            ,array('name'=>'Youtube video making')
            ,array('name'=>'Data science')
            ,array('name'=>'Hardware')
            ,array('name'=>'Dental issues/dentist')
            ,array('name'=>'Physical fitness')
            ,array('name'=>'Physiotherapy')
            ,array('name'=>'Physiotherapy at home')
            ,array('name'=>'Chiropractic/chiropractor')
            ,array('name'=>'Nursing')
            ,array('name'=>'Care at home')
            ,array('name'=>'Acupuncture')
            ,array('name'=>'Acupressure')
            ,array('name'=>'Nutrition/nutritionist')
            ,array('name'=>'Diet consultation')
            ,array('name'=>'Medicine/doctor')
            ,array('name'=>'Surgery')
            ,array('name'=>'Gym')
            ,array('name'=>'Body building')
            ,array('name'=>'Spa')
            ,array('name'=>'Massage')
            ,array('name'=>'Yoga')
            ,array('name'=>'Weight gain')
            ,array('name'=>'Weight loss')
            ,array('name'=>'Spirituality')
            ,array('name'=>'Horoscopes')
            ,array('name'=>'Gem stones')
            ,array('name'=>'Birth stones')
            ,array('name'=>'Parlour')
            ,array('name'=>'Beautician')
            ,array('name'=>'Slimming')
            ,array('name'=>'Real estate')
            ,array('name'=>'Property')
            ,array('name'=>'Vehicle buy/sell')
            ,array('name'=>'Loan')
            ,array('name'=>'Bank loan')
            ,array('name'=>'Wealth management')
            ,array('name'=>'Company registration')
            ,array('name'=>'Tax handling')
            ,array('name'=>'Stock market trading')
            ,array('name'=>'Stock market teaching')
            ,array('name'=>'Law issues')
            ,array('name'=>'Internship')
            ,array('name'=>'Jobs')
            ,array('name'=>'H.R.')
            ,array('name'=>'Business development')
            ,array('name'=>'Business management')
            ,array('name'=>'Tailor')
            ,array('name'=>'Fashion designer')
            ,array('name'=>'Personality development')
            ,array('name'=>'Wedding planning')
            ,array('name'=>'Driving lessons')
            ,array('name'=>'Tourism')
            ,array('name'=>'Travel')
            ,array('name'=>'Medical tourism')
            ,array('name'=>'Cab service')
            ,array('name'=>'Taxi service')
            ,array('name'=>'Wine/pubs/clubs')
            ,array('name'=>'Painting')
            ,array('name'=>'Whitewash')
            ,array('name'=>'Event organising')
            ,array('name'=>'Event management')
            ,array('name'=>'Motivational speaker')
            ,array('name'=>'Mental fitness')
            ,array('name'=>'Psychiatrist')
            ,array('name'=>'Psychologist')
            ,array('name'=>'Admission counselling')
            ,array('name'=>'Career counselling')
            ,array('name'=>'Start up investment')
            ,array('name'=>'Co-working space')
            ,array('name'=>'Office space')
            ,array('name'=>'Video gaming')
            ,array('name'=>'Furniture')
            ,array('name'=>'Interior designing')
            ,array('name'=>'Relationship counseling')
            ,array('name'=>'Mentoring')
            ,array('name'=>'Start up mentoring')
            ,array('name'=>'Teaching')
            ,array('name'=>'Professor')
            ,array('name'=>'Lecturer')
            ,array('name'=>'Hotel booking')
            ,array('name'=>'Video editing')
            ,array('name'=>'Film editing')
            ,array('name'=>'Hair styling')
            ,array('name'=>'Make up')
            ,array('name'=>'Recording')
            ,array('name'=>'Video shooting')
            ,array('name'=>'Sound mixing')
            ,array('name'=>'Sound engineering')
            ,array('name'=>'Photoshoot')
            ,array('name'=>'Party animal')
            ,array('name'=>'Writing')
            ,array('name'=>'Poetry writing')
            ,array('name'=>'Lyrics')
            ,array('name'=>'Screenplay writing')
            ,array('name'=>'Script writing')
            ,array('name'=>'Dialogue writing')
            ,array('name'=>'Novel writing')
            ,array('name'=>'Author')
            ,array('name'=>'Story Writing')
            ,array('name'=>'Essay writing')
            ,array('name'=>'Acting')
            ,array('name'=>'Comedy')
            ,array('name'=>'Direction')
            ,array('name'=>'Cinematography')
            ,array('name'=>'Choreography')
            ,array('name'=>'Food blogging')
            ,array('name'=>'Music composition')
            ,array('name'=>'Play back singing')
            ,array('name'=>'Singing')
            ,array('name'=>'No help needed')
        );
       DB::table('categories')->insert($categories);
    }
}
